<section class="px-4 lg:px-8">
    <h1 class="text-center font-bold text-4xl">About Mr. Altaf Hussain</h1>
    <h2 class="text-center font-bold text-2xl">The Founder & Leader of MQM</h2>

    <p class="mt-4">Altaf Hussain was born in Karachi on 17 September 1953. His parents were immigrants from India. His father, Nazir Hussain, was a Station Master in Indian Railways who, after migrating to Karachi, worked as an office worker ai a local mill. Altaf Husaain's grandfather, the Late Mohammad Mufti Ramazan, was Grand Mufti of the town of Agra in UP, India, and his maternal grandfather. Haji Hafiz Raheem Bhux was a reputed religious scholar in India.</p>

    <p class="mt-4">Altaf Hussain completed his Bachelor of Science from Islamia Science College (Karachi) in 1974, and Bachelor of Pharmacy in 1979 from the University of Karachi. He began his career as a trainee at Karachi’s Seventh Day Adventist Hospital. He also worked simultaneously for a multi-national pharmaceutical company. Between 1970 and 1971, Altaf Hussain joined the National Service Cadet Scheme. Soon afterwards, he was recruited in the Baloch Regiment of the Pakistan Army.</p>

    <p class="mt-4">Mr Hussain has been politically active from a very young age. While attending the University of Karachi, he served as General Secretary and, later, as President of the National Students’ Action Committee. He founded the All-Pakistan Mohajir Students' Organization (APMSO) on the 11 June 1978. The APMSO was formed as an activist group campaigning for the rights of Mohajir students at the University of Karachi. Later, in 1984, It gave birth to the Mohajir Quami Movement (MQM). On 19 June 1992, the Pakistan Government launched the first army operation against the MQM. A month before the operation, because of an attack on his life on 21 December 1991, Mr Hussain fled from Karachi to London where he sought political asylum which was granted to him by the British Government. While in exile, he transformed the Mohajir Quami Movement to Muttahida Quami Movement in 1997 in order to provide a nationwide platform to the oppressed of the country.</p>

    <p class="mt-4">Despite his self-exile, Mr. Hussain holds considerable political influence and power within Pakistan</p>
</section>